version: '3'

services:
  jekyll_docker:
    container_name: jekyll_docker
    image: jekyll/jekyll:latest
    ports:
      - 4000:4000
    volumes:
      - ../:/srv/jekyll:Z
      - ./gem:/usr/gem
    entrypoint: ['sleep', '30m']
